"use client";
import {useState} from "react";
export default function ReportForm(){
 const[form,setForm]=useState({type:"problem_report",reporterName:"",reporterContact:"",description:"",latitude:"",longitude:""}),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const set=(k:string,v:string)=>setForm(x=>({...x,[k]:v}));
 const locate=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>setForm(x=>({...x,latitude:p.coords.latitude.toFixed(6),longitude:p.coords.longitude.toFixed(6)})),()=>setMessage("Could not read your location. Enter the coordinates manually."),{enableHighAccuracy:true,timeout:10000}):setMessage("Location capture is not available on this device.");
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");const payload={...form,latitude:Number(form.latitude),longitude:Number(form.longitude),reporterName:form.reporterName||null,reporterContact:form.reporterContact||null};
 const r=await fetch("/api/reports",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const j=await r.json().catch(()=>({}));setBusy(false);if(!r.ok)return setMessage(j.error?.message||"Report could not be submitted.");setMessage("Report submitted successfully. Reference: "+j.data.id);setForm(x=>({...x,description:""}));}
 return <form className="card stack" onSubmit={submit}><div className="grid two"><div className="field"><label>Report type</label><select value={form.type} onChange={e=>set("type",e.target.value)}><option value="problem_report">Problem / fault</option><option value="small_river_report">Unknown small river / stream</option></select></div><div className="field"><label>Your name (optional)</label><input value={form.reporterName} onChange={e=>set("reporterName",e.target.value)}/></div></div><div className="field"><label>Contact (optional)</label><input value={form.reporterContact} onChange={e=>set("reporterContact",e.target.value)} placeholder="Phone or email"/></div><div className="field"><label>Description</label><textarea required minLength={10} value={form.description} onChange={e=>set("description",e.target.value)} placeholder="Describe what you observed, nearby landmarks, severity, or local name."/></div><div className="grid two"><div className="field"><label>Latitude</label><input required inputMode="decimal" value={form.latitude} onChange={e=>set("latitude",e.target.value)} placeholder="7.7304"/></div><div className="field"><label>Longitude</label><input required inputMode="decimal" value={form.longitude} onChange={e=>set("longitude",e.target.value)} placeholder="8.5361"/></div></div><div className="actions"><button type="button" className="btn" onClick={locate}>Use my current GPS</button><button className="btn primary" disabled={busy}>{busy?"Submitting…":"Submit report"}</button></div>{message&&<div className={message.startsWith("Report submitted")?"success":"notice"}>{message}</div>}</form>;
}
