import {query} from "@/lib/db";
export const dynamic="force-dynamic";
export default async function StaffDashboard(){
 const r=await query(`SELECT
 (SELECT count(*) FROM boreholes) boreholes,(SELECT count(*) FROM boreholes WHERE status='functional') functional,
 (SELECT count(*) FROM assets) assets,(SELECT count(*) FROM forest_sites) forests,(SELECT count(*) FROM rivers WHERE verified) rivers,
 (SELECT count(*) FROM reports WHERE status IN('submitted','under_review','verified')) open_reports,
 (SELECT count(*) FROM boreholes WHERE risk_level IN('high','critical'))+(SELECT count(*) FROM assets WHERE risk_level IN('high','critical'))+(SELECT count(*) FROM forest_sites WHERE risk_level IN('high','critical'))+(SELECT count(*) FROM rivers WHERE risk_level IN('high','critical')) high_risk`);
 const x=r.rows[0],b=Number(x.boreholes||0),rate=b?Math.round(Number(x.functional)*100/b):0;
 const ranking=await query("SELECT entity_type,name,lga_code,risk_score,risk_level FROM (SELECT 'borehole' entity_type,name,lga_code,risk_score,risk_level FROM boreholes UNION ALL SELECT 'asset',name,lga_code,risk_score,risk_level FROM assets UNION ALL SELECT 'forest',name,lga_code,risk_score,risk_level FROM forest_sites UNION ALL SELECT 'river',COALESCE(name,local_name),lga_code,risk_score,risk_level FROM rivers WHERE verified)x ORDER BY risk_score DESC LIMIT 8");
 return <div className="stack"><div className="section-head"><div><h1>Operations dashboard</h1><div className="muted">Live counts from Aiven PostgreSQL/PostGIS.</div></div></div><div className="stats"><div className="stat"><strong>{x.boreholes}</strong><span>Boreholes</span></div><div className="stat"><strong>{rate}%</strong><span>Functional rate</span></div><div className="stat"><strong>{x.open_reports}</strong><span>Open reports</span></div><div className="stat"><strong>{x.high_risk}</strong><span>High-risk items</span></div></div><div className="grid three"><div className="stat"><strong>{x.assets}</strong><span>Assets</span></div><div className="stat"><strong>{x.forests}</strong><span>Forest sites</span></div><div className="stat"><strong>{x.rivers}</strong><span>Verified rivers</span></div></div><div className="card"><h2>Priority ranking</h2><div className="table-wrap"><table><thead><tr><th>Type</th><th>Name</th><th>LGA</th><th>Risk</th><th>Score</th></tr></thead><tbody>{ranking.rows.map((row,i)=><tr key={i}><td>{row.entity_type}</td><td>{row.name||"Unnamed"}</td><td>{row.lga_code}</td><td><span className="badge">{row.risk_level}</span></td><td>{row.risk_score}</td></tr>)}</tbody></table></div></div></div>
}
